all:
	$(MAKE) -C cpab1d
	$(MAKE) -C cpab2d
	$(MAKE) -C cpab3d

clean:
	rm cpab1d/CPAB_ops.cu.o
	rm cpab1d/CPAB_ops.so
	rm cpab2d/CPAB_ops.cu.o
	rm cpab2d/CPAB_ops.so
	rm cpab3d/CPAB_ops.cu.o
	rm cpab3d/CPAB_ops.so
